version: '3'
networks:
  local-spark:
    driver: bridge

services:
  # ───── Other Services ─────

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    networks:
      - local-spark
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    networks:
      local-spark:
        aliases:
          - "spark"
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: PLAINTEXT_INTERNAL://0.0.0.0:29092,PLAINTEXT_C://0.0.0.0:9093,PLAINTEXT_L://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://broker:29092,PLAINTEXT_L://localhost:9092,PLAINTEXT_C://broker:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_L:PLAINTEXT,PLAINTEXT_C:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    networks:
      local-spark:
        aliases:
          - "spark"
    depends_on: 
      - broker
    ports:
      - "7777:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=broker
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=broker:9093
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
      
  spark-master:
    container_name: spark-master
    hostname: spark-master
    build: 
      context: .
      dockerfile: Dockerfile.spark
    image: spark-image
    command: bin/spark-class org.apache.spark.deploy.master.Master
    volumes:
      - ./jobs:/opt/bitnami/spark/jobs
      - ./data/spark-data:/opt/bitnami/spark/data
      - ./utils:/opt/bitnami/spark/utils
      - ./conf:/opt/bitnami/spark/conf
      - ./data/spark-events:/opt/bitnami/spark/events
    environment:
      - SPARK_MODE=master
      - SPARL_MASTER_HOST=spark-master
      - SPARK_LOCAL_IP=spark-master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - SPARK_CONF_DIR=/opt/bitnami/spark/conf
      - SPARK_CONF_FILE=/opt/bitnami/spark/conf/spark-defaults.conf
    ports:
      - "9090:8080"
      - "7077:7077"
    networks:
      local-spark:
        aliases:
          - "spark"

  spark-worker:
    image: spark-image
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    volumes:
      - ./jobs:/opt/bitnami/spark/jobs
      - ./data/spark-data:/opt/bitnami/spark/data
      - ./utils:/opt/bitnami/spark/utils
      - ./conf:/opt/bitnami/spark/conf
      - ./data/spark-events:/opt/bitnami/spark/events
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=3g
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - SPARK_CONF_DIR=/opt/bitnami/spark/conf
      - SPARK_CONF_FILE=/opt/bitnami/spark/conf/spark-defaults.conf
    networks:
      local-spark:
        aliases:
          - "spark"

  spark-history-server:
    container_name: spark-history
    image: spark-image
    command: bin/spark-class org.apache.spark.deploy.history.HistoryServer 
    depends_on:
      - spark-master
    volumes:
      - ./data/spark-events:/opt/bitnami/spark/events
    environment:
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - SPARK_CONF_DIR=/opt/bitnami/spark/conf
      - SPARK_CONF_FILE=/opt/bitnami/spark/conf/spark-defaults.conf
    ports:
      - '18080:18080'
    networks:
      local-spark:
        aliases:
          - "spark"

  mongo:
    image: mongo:latest
    volumes: 
      - "./mongo-data/:/data/db"
    ports:
      - "27017:27017"
    networks:
      local-spark:
        aliases:
          - "spark"
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    networks:
      - local-spark
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - influxdb
      - broker
    environment:
      HOSTNAME: telegraf
      INFLUX_TOKEN: "admin:password"
      INFLUX_ORG: "nyc"
      INFLUX_BUCKET: "mta"
      INFLUX_URL: "http://influxdb:8086"
    restart: always
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    networks:
      local-spark:
        aliases:
          - "spark"
    environment:
      INFLUXDB_DB: mta
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: password
      INFLUXDB_TOKEN: eBcV1gOLKpSIdf4QO_ObP9Uc1tcG0XhDe-DCuHEdFJklUIOqj3-Z54EVn0RYRq7lkxCb1nameSFISrKM2XL6tw==
      INFLUXDB_BUCKET: mta
      INFLUXDB_ORG: nyc
      INFLUXDB_RETENTION: 7d
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ORG: nyc
      DOCKER_INFLUXDB_INIT_BUCKET: mta
      DOCKER_INFLUXDB_INIT_RETENTION: 30d

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      local-spark:
        aliases:
          - "spark"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: password
